

const jobs = [
    {
      id: 1,
      title: "Frontend Developer",
      location: "New York, NY",
      type: "Full-Time",
      company: "ABC Company",
      logo: "https://cdn1.iconfinder.com/data/icons/google-new-logos-1/32/google_chrome_new_logo-512.png",
      description: "We're looking for a frontend developer with experience in React.",
      requirements: ["Experience with React", "CSS proficiency", "Strong communication skills"],
      date: "Apr 26",
      info:
      "Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, a search engine, cloud computing, software, and hardware.",
      infrastructure: ["Cloud computing", "Advertising technologies", "Search engine"],
      goals: ["Organize the world's information and make it universally accessible and useful", "Empower people to use technology to do more and achieve more"]
    },
    {
      id: 2,
      title: "Backend Developer",
      location: "Los Angeles, CA",
      type: "Part-Time",
      company: "XYZ Company",
      logo: "https://www.freepnglogos.com/uploads/apple-logo-png/apple-logo-png-dallas-shootings-don-add-are-speech-zones-used-4.png",
      description: "We're seeking a backend developer with experience in Node.js.",
      requirements: ["Experience with Node.js", "Database proficiency", "Strong problem-solving skills"],
      date: "Apr 25",
    },
    {
      id: 3,
      title: "UX Designer",
      location: "San Francisco, CA",
      type: "Full-Time",
      company: "DEF Company",
      logo: "https://logodownload.org/wp-content/uploads/2014/09/twitter-logo-.png",
      description: "We're looking for a UX designer with a passion for user research.",
      requirements: ["Experience with user research", "Familiarity with design tools", "Strong portfolio"],
      date: "Apr 24",
    },
    {
      id: 4,
      title: "Marketing Coordinator",
      location: "Chicago, IL",
      type: "Summer Job",
      company: "GHI Company",
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.png",
      description: "We're seeking a marketing coordinator to assist with our summer campaign.",
      requirements: ["Excellent communication skills", "Ability to work in a team", "Attention to detail"],
      date: "Apr 23",
    },
    {
      id: 5,
      title: "Sales Associate",
      location: "Miami, FL",
      type: "Full-Time",
      company: "JKL Company",
      logo: "https://companieslogo.com/img/orig/AMZN-e9f942e4.png?t=1632523695",
      description: "We're looking for a sales associate with a proven track record of success.",
      requirements: ["Experience in sales", "Excellent communication skills", "Results-driven"],
      date: "Apr 22",
    },
    {
      id: 6,
      title: "Product Manager",
      location: "Seattle, WA",
      type: "Full-Time",
      company: "MNO Company",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Spotify_logo_without_text.svg/2048px-Spotify_logo_without_text.svg.png",
      description: "We're seeking a product manager with experience in Agile methodologies.",
      requirements: ["Experience in Agile methodologies", "Ability to prioritize tasks", "Strong problem-solving skills"],
      date: "Apr 21",
    },
    {
      id: 7,
      title: "Data Analyst",
      location: "Boston, MA",
      type: "Part-Time",
      company: "PQR Company",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/1024px-Facebook_Logo_%282019%29.png",
      description: "We're looking for a data analyst with experience in SQL and Python.",
      requirements: ["Experience with SQL and Python", "Ability to analyze large datasets", "Strong attention to detail"],
      date: "Apr 20",
    },
    {
      id: 8,
      title: "Graphic Designer",
      location: "Austin, TX",
      type: "Full-Time",
      company: "STU Company",
      logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Instagram_icon.png/2048px-Instagram_icon.png",
      description: "We're seeking a graphic designer with a strong portfolio of design work.",
      requirements: ["Proficiency in design tools", "Strong portfolio", "Ability to work in a team"],
      date: "Apr 19",
      },
      {
      id: 9,
      title: "Content Writer",
      location: "Denver, CO",
      type: "Full-Time",
      company: "VWX Company",
      logo: "https://static.vecteezy.com/system/resources/previews/002/432/911/original/social-media-snapchat-original-latest-logo-free-vector.jpg",
      description: "We're looking for a content writer with experience in SEO.",
      requirements: ["Experience in SEO", "Excellent writing skills", "Ability to work independently"],
      date: "Apr 18",
      },
      {
      id: 10,
      title: "HR Manager",
      location: "Portland, OR",
      type: "Full-Time",
      company: "YZA Company",
      logo: "https://www.freepnglogos.com/uploads/twitch-app-logo-png-3.png",
      description: "We're seeking an HR manager with experience in talent acquisition and retention.",
      requirements: ["Experience in talent acquisition and retention", "Strong communication skills", "Ability to lead a team"],
      date: "Apr 17",
      },
      ];
      export default jobs;